pipeline {
    agent any

    environment {
        PROJECT_ID = 'my-first-devops-project-444911'
        GOOGLE_APPLICATION_CREDENTIALS = credentials('gcp-service-account') // Jenkins credential ID for GCP JSON key
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/saleemafroze/appengine-2025.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    sh '''
                    set -e
                    sudo apt-get update -y
                    sudo apt-get install -y python3-pip python3-dev python3-venv bash
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Deploy to Google App Engine') {
            steps {
                script {
                    sh '''
                    set -e
                    gcloud --version
                    pwd
                    ls -l

                    # Activate service account with credentials from Jenkins
                    echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp-key.json
                    gcloud auth activate-service-account --key-file=gcp-key.json

                    gcloud config set project $PROJECT_ID

                    gcloud app deploy app.yaml --quiet
                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Cleaning up workspace...'
            cleanWs()
        }
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
